### ISSUE TITLE
Error because of validateToken 

### ISSUE THREAD

**Issue by monarkatfactly** [factly/dega-api#103]
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:485:11)
    at ServerResponse.header (/Users/factly/projects/dega/dega-api/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/Users/factly/projects/dega/dega-api/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/Users/factly/projects/dega/dega-api/node_modules/express/lib/response.js:267:15)
    at /Users/factly/projects/dega/dega-api/middleware/errorHandler.js:36:29
    at Layer.handle_error (/Users/factly/projects/dega/dega-api/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/factly/projects/dega/dega-api/node_modules/express/lib/router/index.js:315:13)
    at /Users/factly/projects/dega/dega-api/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/factly/projects/dega/dega-api/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/factly/projects/dega/dega-api/node_modules/express/lib/router/index.js:275:10)
    at /Users/factly/projects/dega/dega-api/node_modules/express/lib/router/index.js:635:15
    at next (/Users/factly/projects/dega/dega-api/node_modules/express/lib/router/index.js:260:14)
    at /Users/factly/projects/dega/dega-api/node_modules/express/lib/router/index.js:635:15
    at next (/Users/factly/projects/dega/dega-api/node_modules/express/lib/router/index.js:260:14)
    at next (/Users/factly/projects/dega/dega-api/node_modules/express/lib/router/route.js:127:14)
    at _rejected (/Users/factly/projects/dega/dega-api/node_modules/q/q.js:864:24)

**Comment by monarkatfactly** [comment]
When client header is not there app sending response 
{
message: 'Client ID is missing',
code: '500-001',
requestId: req.headers['x-request-id'] || null
}

but above error

Probably  because of the way i am handling that in middleware
